[package]
name = "conc-util"
version = "0.5.1"
edition = "2024"
description = "[no_std] utilities for concurrency and async"
license = "MIT"
repository = "https://github.com/KirillAldashkin/RustConcurrencyUtil"
keywords = ["async", "futures", "future", "no_std"]

[features]
default = ["alloc"]
alloc = []

[dependencies]
